### ISSUE TITLE
A3C algorithm - background

### ISSUE THREAD

**Issue by ShaniGam** [rlcode/reinforcement-learning#39]
Amazing work!!
Tried running the A3C algorithm for breakout and it works great!
Where did you get the background information in order to write the code? It's a little bit different than what was explained in the "Asynchronous Methods for Deep Reinforcement Learning" paper.
Thanks :)

**Comment by zzing0907** [comment]
thank you!!
yes, it's little different from "Asyncronous Methods for Deep Reinforcement Learning" paper.
this code don't have local network and don't get gradient directly. but fortunately it works!!
we will update this code to use local network.

we almost refered to [this blog](https://jaromiru.com/2017/03/26/lets-make-an-a3c-implementation/) and change this code to our style.
and we refered to many other codes and paper for finding right hyperparameters.
[this code](https://github.com/dennybritz/reinforcement-learning/tree/master/PolicyGradient/a3c) is helpful.

thanks again @ShaniGam

**Comment by ShaniGam** [comment]
Thanks for the reply. Another question, did you use the epsilon-greedy policy? It seems like the algorithm choose what the network predicts all the time. @zzing0907

**Comment by zzing0907** [comment]
No, we don't use epsilon-greedy but we choose action stochastically. 
actor's output is policy and the policy is probability(because last layer is softmax layer).
agent choose action from probability of each actions, so agent can explore.

thanks. @ShaniGam

**Comment by dnddnjs** [comment]
@ShaniGam
plus to @zzing0907  said, you need to see loss function of optimizer of actor network.
Entropy part of the loss function encourage agent to keep explore.

**Comment by Maschwe** [comment]
Hi all, 
I also have to give you a big compliment to this great work. 
To understand the A3C better could you perhaps provide your grid world example solved by A3C?
With such an easy environment it would be easier to get into it, I guess. 
Regards

**Comment by dnddnjs** [comment]
@Maschwe 
Thank you for your compliment!
Now we are providing A3C code for Cartpole and Breakout.
We think Cartpole is easy enough to understand A3C.
Take a look at cartpole_a3c.py and if you are still confused about A3C, then we will consider
making A3C agent for grid world.

**Comment by Maschwe** [comment]
Wow awesome! Thanks :) 
My thought about implementing A3C for the grid was that you don't have to get familiar with gym. Your grid implementation is so intuitive that someone new almost knows instantaneously whats going on there and can completely concentrate on the algorithm itself ;)  In addition you can also learn how much the environment influences the algorithm, since you can change it. Changing for example the actual input as it is the distances to each single object, to a complete map giving full information about all objects. This would probably require one or two convolutional layer or bigger fully connected layer. All those things are easier to explore and understand when you have the full control about the environment. 
But anyway, thank you very much for the new two examples, I will definitely have a look into your new implementations :+1:

**Comment by dnddnjs** [comment]
I am interesting about what you are saying about adapting CNN to grid world. Thank you for your compliment!

**Comment by Maschwe** [comment]
Hi, 

 

I’m not sure whether this works or not but I try to reply here. 

I meant that you probably need to implement a CNN when you give the whole Map information back as a state. 

For example a 10 times 10 matrix with ones in the position of free space, zeros where walls are, 0.75 where the agent is and 0.25 where the target is. Then the agent could learn to avoid obstacles in general since he could learn that obstacles are represented by a zero and every time he steps on it he gets a huge negative reward. 

 

Regards, 

 

Martin 

 

Von: Leewoongwon [mailto:notifications@github.com] 
Gesendet: Samstag, 24. Juni 2017 10:35
An: rlcode/reinforcement-learning <reinforcement-learning@noreply.github.com>
Cc: Schweigler, Martin <schweigler@embedded.rwth-aachen.de>; Mention <mention@noreply.github.com>
Betreff: Re: [rlcode/reinforcement-learning] A3C algorithm - background (#39)

 

I am interesting about what you are saying about adapting CNN to grid world. Thank you for your compliment!

**Comment by ShaniGam** [comment]
How many days did it take until it converged in breakout_a3c? Did you try using LSTM for faster convergence?

**Comment by akileshbadrinaaraayanan** [comment]
I am trying to implement A3C for gridworld by appropriately modifying run() method of A3C cartpole example. However, I am getting the below error: 

Exception ignored in: <bound method PhotoImage.__del__ of <PIL.ImageTk.PhotoImage object at 0x7f7b807077b8>>
Traceback (most recent call last):
  File "/home/akb/.local/lib/python3.4/site-packages/PIL/ImageTk.py", line 130, in __del__
    name = self.__photo.name
AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "deep_a3c.py", line 159, in run
    env = Env()
  File "/home/akb/reinforcement-learning/1-grid-world/6-deep-sarsa/environment_a3c.py", line 21, in __init__
    self.shapes = self.load_images()
  File "/home/akb/reinforcement-learning/1-grid-world/6-deep-sarsa/environment_a3c.py", line 58, in load_images
    Image.open("../img/rectangle.png").resize((30, 30)))
  File "/home/akb/.local/lib/python3.4/site-packages/PIL/ImageTk.py", line 124, in __init__
    self.__photo = tkinter.PhotoImage(**kw)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 3419, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 3375, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
RuntimeError: main thread is not in main loop

Any help on this error. If possible, could you provide an implementation of A3C on Gridworld.

Thanks,
Akilesh
